Consider the below code to answer further questions:

In [4]:
import numpy as np
list_ = ['1' , '2' , '3', '4' , '5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Arrays need to be declared. Lists don't, since they are built into Python. In the examples above, you saw that lists are created by simply enclosing a sequence of elements into square brackets. Creating an array, on the other hand, requires a specific function from either the array module (i.e., array.array()) or NumPy package (i.e., numpy.array()). Because of this, lists are used more often than arrays.

Arrays can store data very compactly and are more efficient for storing large amounts of data.

Arrays are great for numerical operations; lists cannot directly handle math operations. For example, you can divide each element of an array by the same number with just one line of code. If you try the same with a list, you'll get an error.

In [5]:
array = np.array([3, 6, 9, 12])
division = array/3
print(division)
print (type(division))

[1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [6]:
list = [3, 6, 9, 12]
division = list/3

TypeError: unsupported operand type(s) for /: 'list' and 'int'

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [7]:
# array_list
array_list.dtype

dtype('<U1')

In [8]:
for i in array_list: print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [9]:
# list_
for i in list_: print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


Q3. Considering the following changes in the variable, array_list:

In [10]:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Consider the below code to answer further questions:

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
type(num_list)



In [20]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
type(num_array)

numpy.ndarray

In [21]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_list


[[1, 2, 3], [4, 5, 6]]

In [22]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape


(ii) size

In [23]:
#  shape
num_array.shape

(2, 3)

In [24]:
# size
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [31]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.matrix(np.zeros((3,3)))

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [37]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.matrix(np.eye(5))

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])